# Generated by Django 5.2.11 on 2026-02-27 09:39
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [VectorExtension()]
